package main

// DO NOT MODIFY: generated by github.com/ttacon/toml2cli
// If you need to make changes, update the toml config and then regenerate
// this file.

import (
	"log"
	"os"

	cli "github.com/urfave/cli/v2"
)

func main() {
	app := cli.NewApp()
	app.Name = "autumn"
	app.Usage = "A code generation tool that helps you relax"

	app.Commands = []*cli.Command{
		&cli.Command{
			Name:        "version",
			Action:      version,
			Description: "Print out the current version",
		},
	}
	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
