[general]
name = "autumn"
description = "A code generation tool that helps you relax"
generator = "github.com/urfave/cli"


[[command]]
name = "version"
description = "Print out the current version"
action = "version"

[[command]]
name = "init"
description = "Initialize an autumn configuration file"
action = "initCommand"

[[command.flags]]
type = "bool"
name = "force"
aliases = [ "f" ]
description = "Force creating a new config file even if one exists"
value = false

[[command]]
name = "get"
description = "Retrieve all frameworks."
action = "get"

[[command]]
name = "plan"
description = "Plan the code to generate."
action = "plan"

[[command.flags]]
type = "string"
name = "out"
aliases = [ "o" ]
description = "The output file to write the plan to."
value = "autumn-plan.json"

[[command.flags]]
type = "bool"
name = "force"
aliases = [ "f" ]
description = "Force creating a new plan file even if one exists"
value = false
