name: Unit Testing

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Unit testing coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.17

      - name: Check out source code
        uses: actions/checkout@v3.0.0

      - name: Dependencies
        run: go get ./...

      - name: Build
        run: go build ./...

      - name: Test
        run: |
          go test -v ./... -coverprofile coverage.out -covermode count
          go tool cover -func coverage.out
      # Code pulled from this example: https://medium.com/synechron/how-to-set-up-a-test-coverage-threshold-in-go-and-github-167f69b940dc
      - name: Quality Gate - Test coverage shall be above threshold
        env:
          TESTCOVERAGE_THRESHOLD: 50.0
        run: |
          echo "Quality Gate: checking test coverage is above threshold ..."
          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          echo "Current test coverage : $totalCoverage %"
          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
            echo "OK"
          else
            echo "Current test coverage is below threshold. Please add more unit tests."
            echo "Failed"
            exit 1
          fi
